name: quiz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  vrouter: ^1.2.1
  http: ^0.13.5
  cloud_firestore: ^3.4.7
  firebase_core: ^1.22.0
  get_it: ^7.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true