name: quiz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-171.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  vrouter: ^1.2.1
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true